### ISSUE TITLE
Using op-sqlite gives me a 'Multiple commands produce 'op-sqlite/op_sqlite.framework/Headers/libsql.h' error

### ISSUE THREAD

**Issue by G2Jose** [powersync-ja/powersync-js#627]
```
@op-engineering/op-sqlite: 14.0.3
@powersync/op-sqlite: ^0.6.1
@powersync/react-native: 1.20.3
```

Switching from @journeyapps/react-native-quick-sqlite to @powersync/op-sqlite + @op-engineering/op-sqlite gives me a build error on Xcode: 
> Multiple commands produce 'op-sqlite/op_sqlite.framework/Headers/libsql.h

**Comment by G2Jose** [comment]
Was able to get around it by using this patch (documenting here in case anyone else runs into it, but I'm hoping something can be changed on the library level so this manual patch isn't required) 


```diff
# @op-engineering-op-sqlite-npm-14.0.3-d53c83358f.patch
diff --git a/ios/libsql.xcframework/ios-arm64_x86_64-simulator/Headers/libsql.h b/ios/libsql.xcframework/ios-arm64_x86_64-simulator/Headers/libsql.h
deleted file mode 100644
index 505c4b291d9166e46019d51c77d23ba9c92d0dee..0000000000000000000000000000000000000000
--- a/ios/libsql.xcframework/ios-arm64_x86_64-simulator/Headers/libsql.h
+++ /dev/null
@@ -1,173 +0,0 @@
-#ifndef LIBSQL_EXPERIMENTAL_H
-#define LIBSQL_EXPERIMENTAL_H
-
-#include <stdint.h>
-
-#define LIBSQL_INT 1
-
-#define LIBSQL_FLOAT 2
-
-#define LIBSQL_TEXT 3
-
-#define LIBSQL_BLOB 4
-
-#define LIBSQL_NULL 5
-
-typedef struct libsql_connection libsql_connection;
-
-typedef struct libsql_database libsql_database;
-
-typedef struct libsql_row libsql_row;
-
-typedef struct libsql_rows libsql_rows;
-
-typedef struct libsql_rows_future libsql_rows_future;
-
-typedef struct libsql_stmt libsql_stmt;
-
-typedef const libsql_database *libsql_database_t;
-
-typedef struct {
-  int frame_no;
-  int frames_synced;
-} replicated;
-
-typedef struct {
-  const char *db_path;
-  const char *primary_url;
-  const char *auth_token;
-  char read_your_writes;
-  const char *encryption_key;
-  int sync_interval;
-  char with_webpki;
-  char offline;
-} libsql_config;
-
-typedef const libsql_connection *libsql_connection_t;
-
-typedef const libsql_stmt *libsql_stmt_t;
-
-typedef const libsql_rows *libsql_rows_t;
-
-typedef const libsql_rows_future *libsql_rows_future_t;
-
-typedef const libsql_row *libsql_row_t;
-
-typedef struct {
-  const char *ptr;
-  int len;
-} blob;
-
-#ifdef __cplusplus
-extern "C" {
-#endif // __cplusplus
-
-int libsql_enable_internal_tracing(void);
-
-int libsql_sync(libsql_database_t db, const char **out_err_msg);
-
-int libsql_sync2(libsql_database_t db, replicated *out_replicated, const char **out_err_msg);
-
-int libsql_open_sync(const char *db_path,
-                     const char *primary_url,
-                     const char *auth_token,
-                     char read_your_writes,
-                     const char *encryption_key,
-                     libsql_database_t *out_db,
-                     const char **out_err_msg);
-
-int libsql_open_sync_with_webpki(const char *db_path,
-                                 const char *primary_url,
-                                 const char *auth_token,
-                                 char read_your_writes,
-                                 const char *encryption_key,
-                                 libsql_database_t *out_db,
-                                 const char **out_err_msg);
-
-int libsql_open_sync_with_config(libsql_config config, libsql_database_t *out_db, const char **out_err_msg);
-
-int libsql_open_ext(const char *url, libsql_database_t *out_db, const char **out_err_msg);
-
-int libsql_open_file(const char *url, libsql_database_t *out_db, const char **out_err_msg);
-
-int libsql_open_remote(const char *url, const char *auth_token, libsql_database_t *out_db, const char **out_err_msg);
-
-int libsql_open_remote_with_webpki(const char *url,
-                                   const char *auth_token,
-                                   libsql_database_t *out_db,
-                                   const char **out_err_msg);
-
-void libsql_close(libsql_database_t db);
-
-int libsql_connect(libsql_database_t db, libsql_connection_t *out_conn, const char **out_err_msg);
-
-int libsql_load_extension(libsql_connection_t conn,
-                          const char *path,
-                          const char *entry_point,
-                          const char **out_err_msg);
-
-int libsql_reset(libsql_connection_t conn, const char **out_err_msg);
-
-void libsql_disconnect(libsql_connection_t conn);
-
-int libsql_prepare(libsql_connection_t conn, const char *sql, libsql_stmt_t *out_stmt, const char **out_err_msg);
-
-int libsql_bind_int(libsql_stmt_t stmt, int idx, long long value, const char **out_err_msg);
-
-int libsql_bind_float(libsql_stmt_t stmt, int idx, double value, const char **out_err_msg);
-
-int libsql_bind_null(libsql_stmt_t stmt, int idx, const char **out_err_msg);
-
-int libsql_bind_string(libsql_stmt_t stmt, int idx, const char *value, const char **out_err_msg);
-
-int libsql_bind_blob(libsql_stmt_t stmt, int idx, const unsigned char *value, int value_len, const char **out_err_msg);
-
-int libsql_query_stmt(libsql_stmt_t stmt, libsql_rows_t *out_rows, const char **out_err_msg);
-
-int libsql_execute_stmt(libsql_stmt_t stmt, const char **out_err_msg);
-
-int libsql_reset_stmt(libsql_stmt_t stmt, const char **out_err_msg);
-
-void libsql_free_stmt(libsql_stmt_t stmt);
-
-int libsql_query(libsql_connection_t conn, const char *sql, libsql_rows_t *out_rows, const char **out_err_msg);
-
-int libsql_execute(libsql_connection_t conn, const char *sql, const char **out_err_msg);
-
-void libsql_free_rows(libsql_rows_t res);
-
-void libsql_free_rows_future(libsql_rows_future_t res);
-
-void libsql_wait_result(libsql_rows_future_t res);
-
-int libsql_column_count(libsql_rows_t res);
-
-int libsql_column_name(libsql_rows_t res, int col, const char **out_name, const char **out_err_msg);
-
-int libsql_column_type(libsql_rows_t res, libsql_row_t row, int col, int *out_type, const char **out_err_msg);
-
-uint64_t libsql_changes(libsql_connection_t conn);
-
-int64_t libsql_last_insert_rowid(libsql_connection_t conn);
-
-int libsql_next_row(libsql_rows_t res, libsql_row_t *out_row, const char **out_err_msg);
-
-void libsql_free_row(libsql_row_t res);
-
-int libsql_get_string(libsql_row_t res, int col, const char **out_value, const char **out_err_msg);
-
-void libsql_free_string(const char *ptr);
-
-int libsql_get_int(libsql_row_t res, int col, long long *out_value, const char **out_err_msg);
-
-int libsql_get_float(libsql_row_t res, int col, double *out_value, const char **out_err_msg);
-
-int libsql_get_blob(libsql_row_t res, int col, blob *out_blob, const char **out_err_msg);
-
-void libsql_free_blob(blob b);
-
-#ifdef __cplusplus
-} // extern "C"
-#endif // __cplusplus
-
-#endif /* LIBSQL_EXPERIMENTAL_H */

```

**Comment by airo-email** [comment]
also getting this issue

**Comment by Chriztiaan** [comment]
Does this issue go away if you pin to `@powersync/op-sqlite: 0.6.1`? Would be good to know if it's a regression with version 0.0.7.

**Comment by stevensJourney** [comment]
Interestingly, it looks like the `libsql.h` header should be [excluded](https://github.com/OP-Engineering/op-sqlite/blob/c728becc10a23a005947e3b8edab86d6a4f15832/op-sqlite.podspec#L139) from the build if using SQLCipher or "Vanilla OP-SQLite". The libsql framework should also not be [included](https://github.com/OP-Engineering/op-sqlite/blob/c728becc10a23a005947e3b8edab86d6a4f15832/op-sqlite.podspec#L188) unless if `"libsql": true` is defined in the app [package.json](https://github.com/OP-Engineering/op-sqlite/blob/c728becc10a23a005947e3b8edab86d6a4f15832/example/package.json#L66). Are you perhaps using `libsql`?

**Comment by G2Jose** [comment]
Haven't had a chance to try downgrading @Chriztiaan, but can confirm that it's still an issue on `@op-engineering/op-sqlite: 15.0.1`

**Comment by LucaL1fe** [comment]
Do we have a (real) solution for this?

**Comment by Chriztiaan** [comment]
Hey @LucaL1fe, it's hard to suggest a fix unless we know what your setup/config looks like. 
Beyond what has been suggested (libsql=true option), I would have to ask for a minimal reproducible example of the problem - potentially just a small repo.

**Comment by LucaL1fe** [comment]
@Chriztiaan 

# iOS Build Failure: SQLite3 Redefinition Errors with PowerSync + op-sqlite on Expo EAS

## Issue Description

After upgrading to the latest versions of PowerSync and op-sqlite packages, iOS builds on Expo EAS are failing with SQLite3 symbol redefinition errors. Everything was working perfectly on PowerSync 1.24.1, but the latest version causes build failures.

## Error Message

```
🍏 iOS build failed
The "Run fastlane" step failed during the Xcode build with the following errors:
redefinition of sqlite3_file
redefinition of sqlite3_io_methods
redefinition of sqlite3_vfs
redefinition of sqlite3_mem_methods
redefinition of sqlite3_module
redefinition of sqlite3_index_info
redefinition of sqlite3_index_constraint
redefinition of sqlite3_index_orderby
redefinition of sqlite3_index_constraint_usage
redefinition of sqlite3_vtab
redefinition of sqlite3_vtab_cursor
redefinition of sqlite3_mutex_methods
redefinition of sqlite3_pcache_page
redefinition of sqlite3_pcache_methods2
redefinition of sqlite3_pcache_methods
redefinition of sqlite3_snapshot
typedef redefinition with different types (struct … vs struct sqlite3_snapshot)
could not build Objective-C module SQLite3
```

## Environment

- **Platform**: Windows (cannot build iOS locally)
- **Build Service**: Expo EAS
- **Expo SDK**: 53.0.22
- **React Native**: 0.79.5

## Configuration Files

### package.json
```json
{
  "name": "rewardpoints",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "lint": "expo lint"
  },
  "dependencies": {
    "@azure/core-asynciterator-polyfill": "^1.0.2",
    "@babel/plugin-transform-async-generator-functions": "^7.28.0",
    "@expo/vector-icons": "^14.1.0",
    "@op-engineering/op-sqlite": "^14.1.4",
    "@powersync/op-sqlite": "^0.7.8",
    "@powersync/react": "^1.7.3",
    "@powersync/react-native": "^1.24.2",
    "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-community/netinfo": "11.4.1",
    "@react-native-google-signin/google-signin": "^21.0.0",
    "@supabase/supabase-js": "^2.55.0",
    "expo": "53.0.22",
    "expo-apple-authentication": "~7.2.4",
    "expo-dev-client": "~5.2.4",
    "expo-router": "~5.1.5",
    "react": "19.0.0",
    "react-native": "0.79.5",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-get-random-values": "~1.11.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "zustand": "^5.0.8"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/react": "~19.0.10",
    "typescript": "~5.8.3"
  }
}
```

### app.json
```json
{
  "expo": {
    "name": "rewardpoints",
    "slug": "rewardpoints",
    "version": "1.0.0",
    "orientation": "portrait",
    "scheme": "rewardpoints",
    "userInterfaceStyle": "dark",
    "newArchEnabled": true,
    "ios": {
      "usesAppleSignIn": true,
      "supportsTablet": true,
      "bundleIdentifier": "com.lucal1fe.rewardpoints"
    },
    "android": {
      "package": "com.lucal1fe.rewardpoints",
      "allowBackup": false
    },
    "plugins": [
      "expo-router",
      "expo-apple-authentication",
      "@react-native-google-signin/google-signin"
    ]
  }
}
```

### metro.config.js
```javascript
const { getDefaultConfig } = require("expo/metro-config")
const config = getDefaultConfig(__dirname)

config.transformer.getTransformOptions = async () => ({
  transform: {
    inlineRequires: {
      blockList: {
        [require.resolve('@powersync/react-native')]: true
      }
    }
  }
})

module.exports = config
```

### babel.config.js
```javascript
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      '@babel/plugin-transform-async-generator-functions'
    ]
  };
};
```

### database.ts (PowerSync setup)
```typescript
import { OPSqliteOpenFactory } from '@powersync/op-sqlite';
import { createBaseLogger, LogLevel, PowerSyncDatabase } from '@powersync/react-native';
import { AppSchema } from './schema';

const logger = createBaseLogger();
logger.useDefaults();
logger.setLevel(LogLevel.INFO);

const factory = new OPSqliteOpenFactory({
  dbFilename: 'rewardpoints.sqlite'
})

export const powerSync = new PowerSyncDatabase({
  database: factory,
  schema: AppSchema,
  logger: logger
})
```

### eas.json
```json
{
  "cli": {
    "version": ">= 16.17.4",
    "appVersionSource": "remote"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "cache": {
        "disabled": true
      }
    },
    "production": {
      "autoIncrement": true
    }
  }
}
```

## Additional Information

- Android builds work fine with the same configuration
- The issue only occurs on iOS builds through EAS
- This seems to be a conflict between SQLite3 symbols from different sources
- Building on Windows, so cannot test iOS builds locally

## Question

Is this a known issue with the latest PowerSync/op-sqlite versions? Are there any workarounds or configuration changes needed to resolve the SQLite3 symbol conflicts on iOS builds?

**Comment by LucaL1fe** [comment]
# Solution: iOS Build Failure - SQLite3 Redefinition Errors with PowerSync + op-sqlite on Expo EAS

## ✅ SOLVED

The issue is caused by a conflict between SQLite dependencies in PowerSync and expo-updates. Both packages include SQLite, leading to symbol redefinition errors during iOS builds.

## Root Cause

PowerSync and expo-updates both depend on SQLite3, but they include different versions or implementations. When building for iOS, the linker encounters duplicate symbol definitions and fails the build.

## Solution

The fix is to configure iOS builds to use a third-party SQLite pod that both packages can share. This is done through an Expo config plugin that creates the necessary iOS configuration during the EAS build process.

### Step 1: Create the Expo Config Plugin

Create a new file `plugins/withPowerSyncSQLite.js`:

```javascript
const { withDangerousMod, withPlugins } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Expo Config Plugin to configure iOS to use third-party SQLite pod
 * This resolves conflicts between PowerSync and expo-updates SQLite dependencies
 * 
 * Creates ios/Podfile.properties.json with the required configuration
 * for PowerSync to work properly with Expo Updates
 */
function withPowerSyncSQLite(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const iosPath = path.join(projectRoot, 'ios');
      const podfilePropertiesPath = path.join(iosPath, 'Podfile.properties.json');

      // Ensure ios directory exists (it will be created by EAS during build)
      if (!fs.existsSync(iosPath)) {
        fs.mkdirSync(iosPath, { recursive: true });
      }

      // Read existing Podfile.properties.json or create new object
      let podfileProperties = {};
      if (fs.existsSync(podfilePropertiesPath)) {
        try {
          const content = fs.readFileSync(podfilePropertiesPath, 'utf8');
          podfileProperties = JSON.parse(content);
        } catch (error) {
          console.warn('Failed to parse existing Podfile.properties.json, creating new one');
        }
      }

      // Add the third-party SQLite configuration
      podfileProperties['expo.updates.useThirdPartySQLitePod'] = 'true';

      // Write the updated configuration
      fs.writeFileSync(
        podfilePropertiesPath,
        JSON.stringify(podfileProperties, null, 2)
      );

      console.log('✅ Configured iOS to use third-party SQLite pod for PowerSync compatibility');

      return config;
    },
  ]);
}

module.exports = withPowerSyncSQLite;
```

### Step 2: Update app.json

Add the plugin to your `app.json` configuration:

```json
{
  "expo": {
    "name": "rewardpoints",
    "slug": "rewardpoints",
    "version": "1.0.0",
    "orientation": "portrait",
    "scheme": "rewardpoints",
    "userInterfaceStyle": "dark",
    "newArchEnabled": true,
    "ios": {
      "usesAppleSignIn": true,
      "supportsTablet": true,
      "bundleIdentifier": "com.lucal1fe.rewardpoints"
    },
    "android": {
      "package": "com.lucal1fe.rewardpoints",
      "allowBackup": false
    },
    "plugins": [
      "expo-router",
      "expo-apple-authentication",
      "@react-native-google-signin/google-signin",
      "./plugins/withPowerSyncSQLite"  // ← Add this line
    ]
  }
}
```

## How It Works

1. **The Plugin**: Uses Expo's config plugin system to modify the iOS build configuration
2. **withDangerousMod**: Provides direct file system access during the prebuild process (it's called "dangerous" because it bypasses Expo's normal safety mechanisms, but it's perfectly safe when used correctly)
3. **Podfile.properties.json**: Creates this configuration file that tells CocoaPods to use a shared third-party SQLite pod
4. **EAS Build**: The plugin runs on EAS servers during the build process, not on your local Windows machine

## Why This Works on Windows

Since you're building on Windows and can't test iOS locally, this solution is perfect because:
- The plugin runs on EAS build servers, not your local machine
- No need to manually edit iOS files or have access to Xcode
- The configuration is applied automatically during each build

## Verification

After applying this fix:
1. Commit the changes to your repository
2. Run `eas build --platform ios`
3. The build should now complete successfully without SQLite redefinition errors

## Additional Notes

- This solution is based on the official PowerSync documentation: https://github.com/powersync-ja/powersync-js/blob/main/packages/react-native/README.md
- The fix only affects iOS builds; Android builds continue to work normally
- The plugin is idempotent - running it multiple times won't cause issues

**Comment by Chriztiaan** [comment]
Thanks for following up with the workaround @LucaL1fe, FWIW if I follow the iOS Build Failure steps and I build for iOS on my Mac I get no issues.

**Comment by Chriztiaan** [comment]
@G2Jose would be good to know whether this alleviates the problem on your side.

**Comment by LucaL1fe** [comment]
@Chriztiaan  

On Windows, the approach from the docs doesn’t work for me. The docs say:  

**Expo EAS config (optional)**  
If you are using this library in an Expo project and encounter issues with multiple versions of SQLite3, the conflict might be due to `expo-updates` also depending on SQLite. To resolve this, you can configure Expo to use the third-party SQLite pod by adding this to `ios/Podfile.properties.json`:  

    {
      "expo.updates.useThirdPartySQLitePod": "true"
    }

The problem is: I can’t build iOS projects on Windows, so that step doesn’t work here (at least for me). What the Podfile does for you on macOS/iOS, I solve with this plugin.  

Basically, it’s all about setting:  

    "expo.updates.useThirdPartySQLitePod": "true"
